[package]
name = "bb_server_macros"
version = "0.2.0"
edition = "2021"

[dependencies]
syn = { version = "1.0", features = ["full", "extra-traits"] }
quote = "1.0.9"
proc-macro2 = "1.0.24"
proc-macro-error = "1.0"

[lib]
proc-macro = true
